# Generated by Django 4.1.13 on 2024-07-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0006_alter_testimonial_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
