# Generated by Django 4.1.13 on 2024-07-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0007_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='phone',
            field=models.CharField(default='hello', max_length=20),
        ),
        migrations.AddField(
            model_name='about',
            name='section',
            field=models.CharField(default='hello', max_length=200),
        ),
    ]
