# Generated by Django 4.1.13 on 2024-07-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0008_about_phone_about_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='about',
            name='section',
            field=models.CharField(max_length=200),
        ),
    ]
