# Generated by Django 4.1.13 on 2024-07-03 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0009_alter_about_phone_alter_about_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
    ]
