# Generated by Django 4.1.13 on 2024-07-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0011_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='section',
            new_name='title',
        ),
        migrations.AddField(
            model_name='about',
            name='sections',
            field=models.CharField(default='h', max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.CharField(default='h', max_length=20),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
