# Generated by Django 4.1.13 on 2024-07-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0012_rename_section_about_title_about_sections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='about',
            name='sections',
            field=models.CharField(max_length=200),
        ),
    ]
