# Generated by Django 4.1.13 on 2024-07-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0013_alter_about_phone_alter_about_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='sections',
            field=models.TextField(max_length=200),
        ),
    ]
