# Generated by Django 4.1.13 on 2024-07-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0016_quote_alter_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
    ]
