# Generated by Django 4.1.13 on 2024-07-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0017_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='feature_pics'),
        ),
    ]
