# Generated by Django 4.1.13 on 2024-07-03 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0018_feature_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_images')),
                ('uploaded_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
