# Generated by Django 4.1.13 on 2024-07-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0019_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='feature_pics')),
            ],
        ),
    ]
