# Generated by Django 4.1.13 on 2024-07-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0021_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='subtitle',
            field=models.CharField(default='d', max_length=200),
        ),
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(default='d', max_length=120),
        ),
    ]
