# Generated by Django 4.1.13 on 2024-07-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0022_slider_subtitle_slider_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='subtitle',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
