# Generated by Django 4.1.13 on 2024-07-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0023_alter_slider_subtitle_alter_slider_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=200)),
                ('business_type', models.CharField(max_length=200)),
                ('features_need', models.TextField()),
                ('features_noneed', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_duration', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='sections',
            field=models.TextField(),
        ),
    ]
