# Generated by Django 4.1.13 on 2024-07-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0024_price_alter_about_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='time_duration',
            field=models.CharField(choices=[('MONTH', 'Month'), ('YEAR', 'Year')], default='MONTH', max_length=5),
        ),
    ]
