# Generated by Django 4.1.13 on 2024-07-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0026_technology_remove_price_features_need_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='features_need',
            field=models.ManyToManyField(related_name='needed_in_plans', to='startup.technology'),
        ),
        migrations.AlterField(
            model_name='price',
            name='features_noneed',
            field=models.ManyToManyField(blank=True, related_name='not_needed_in_plans', to='startup.technology'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(default='h', max_length=200),
        ),
    ]
