# Generated by Django 4.1.13 on 2024-07-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0027_alter_price_features_need_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
