# Generated by Django 4.1.13 on 2024-07-05 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0028_alter_technology_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='features_need',
            new_name='technology_need',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='features_noneed',
            new_name='technology_noneed',
        ),
    ]
