# Generated by Django 4.1.13 on 2024-07-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0029_rename_features_need_price_technology_need_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='h', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='sections',
        ),
        migrations.AddField(
            model_name='about',
            name='qualities',
            field=models.ManyToManyField(related_name='qualities', to='startup.quality'),
        ),
    ]
