# Generated by Django 4.1.13 on 2024-07-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0031_alter_quality_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(default='defaultvendor.jpg', upload_to='vendor_pics')),
            ],
        ),
    ]
