# Generated by Django 4.1.13 on 2024-07-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0032_vendorimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(default='defaultvendor.jpg', upload_to='vendor_pics')),
            ],
        ),
    ]
